package:
  name: qt6-qtshadertools
  version: "6.9.1"
  epoch: 0
  description: qtshadertools
  copyright:
    - license: LGPL-3.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - cmake
      - libglvnd-dev
      - qt6-qtbase-dev
      - libxkbcommon-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 661130571df1a19bd10dd7705fe689cfde835dad
      repository: https://code.qt.io/qt/qtshadertools.git
      tag: v${{package.version}}


  - uses: cmake/configure

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

update:
  enabled: true
  git:
    strip-prefix: v


subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development libraries and headers
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check
        - uses: test/pkgconf

