package:
  name: qt6-qtwebengine
  version: "6.9.2"
  epoch: 0
  description: qtwebengine
  copyright:
    - license: LGPL-3.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - cmake
      - libglvnd-dev
      - qt6-qtbase-dev
     # - libxkbcommon-dev
      - qt6-qtdeclarative-dev
      - qt6-qtshadertools-dev
     # - qt6-qtconnectivity-dev
      - libpng-dev
      - tiff-dev
      - re2-dev
      - icu-dev
      - opus-dev
      - libva-dev
      - libvpx-dev
      - libpng-dev
      - tiff-dev
      - python3-dev
      - perl-dev
      - flex
      - bison
      - gperf
      - dbus-dev
      - nss
      - fontconfig-dev
      - harfbuzz-dev
      - glib-dev
      - py3-html5lib

var-transforms:
  - from: ${{package.version}}
    match: "_"
    replace: "-"
    to: mangled-package-version

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/qt/qtwebengine
      tag: v${{vars.mangled-package-version}}
      expected-commit: 997e3a38136b7cd69b9a79d5cd7a77448c9cfb33
      recurse-submodules: true

  #- runs: exit 1

  - uses: cmake/configure
    with:
      opts: |
        -DQT_FEATURE_webengine_system_alsa=ON \
        -DQT_FEATURE_webengine_system_ffmpeg=ON \
        -DQT_FEATURE_webengine_system_icu=ON \
        -DQT_FEATURE_webengine_system_libevent=ON \
        -DQT_FEATURE_webengine_system_libpci=ON \
        -DQT_FEATURE_webengine_system_libpng=ON \
        -DQT_FEATURE_webengine_system_libwebp=ON \
        -DQT_FEATURE_webengine_system_libxml=ON \
        -DQT_FEATURE_webengine_system_minizip=ON \
        -DQT_FEATURE_webengine_system_opus=ON \
        -DQT_FEATURE_webengine_system_pulseaudio=ON \
        -DQT_FEATURE_webengine_system_zlib=ON \
        -DQT_FEATURE_webengine_proprietary_codecs=ON \
        -DQT_FEATURE_webengine_kerberos=ON \
        -DQT_FEATURE_webengine_webrtc_pipewire=ON

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

update:
  enabled: true
  github:
    identifier: qt/qtwebengine
    use-tag: true
    strip-prefix: v
  ignore-regex-patterns:
    - 'rc\d+$'
    - 'beta\d+$'

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development libraries and headers
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check
        - uses: test/pkgconf

test:
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/pkgconf
