package:
  name: qt6-qtwayland
  version: "6.9.1"
  epoch: 0
  description: qtwayland
  copyright:
    - license: LGPL-3.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - cmake
      - libglvnd-dev
      - qt6-qtbase-dev
      - libxkbcommon-dev
      - wayland-dev
      - wayland-protocols

var-transforms:
  - from: ${{package.version}}
    match: "_"
    replace: "-"
    to: mangled-package-version

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/qt/qtwayland
      tag: v${{package.version}}
      expected-commit: b54d446eb64ef23a5e365d5b6ff6116c3a5b6051

  - uses: cmake/configure

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

update:
  enabled: true
  github:
    identifier: qt/qtwayland
    use-tag: true
    strip-prefix: v
  ignore-regex-patterns:
    - 'rc\d+$'
    - 'beta\d+$'

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} development libraries and headers
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check
        - uses: test/pkgconf

test:
  pipeline:
    - uses: test/tw/ldd-check
    - uses: test/pkgconf
